<div class="container text-center">
    <h2>Home page</h2>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut est mauris, euismod eu felis in, sollicitudin varius neque. In hac habitasse platea dictumst. Nullam erat magna, porttitor eget ornare et, tristique quis massa. Mauris non suscipit sapien. Nam diam risus, aliquam vel purus at, mollis venenatis tortor. Suspendisse et porttitor mi, at ultrices tortor. Nulla facilisi. Pellentesque sed elit lectus. Aenean felis lacus, cursus a consectetur vitae, blandit ut erat. Vestibulum nisi ipsum, lobortis et placerat rutrum, varius sed erat. Integer eget blandit risus, ut varius justo.</p>
        </div>
        <div class='col-md-6'>
            <p>Mauris lorem nunc, tristique a diam in, laoreet viverra eros. Praesent eros lacus, viverra eu neque ut, scelerisque sodales ligula. Aenean commodo nisi sed malesuada lacinia. Morbi vulputate augue in libero suscipit, vitae tincidunt risus sagittis. Curabitur blandit sem non tristique bibendum. Vivamus id enim sollicitudin, eleifend orci id, eleifend enim. Nunc eros sem, consectetur eget volutpat sit amet, aliquet non erat. Nunc rutrum accumsan eleifend. Curabitur egestas metus tellus. Sed id efficitur velit. Maecenas eu orci in felis blandit varius. Proin sit amet ipsum arcu. Nam condimentum auctor turpis id interdum. Proin eget augue at leo tincidunt mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        </div>
        <a href="test123" target="_blank" rel="noopener noreferrer">Test123</a>
    </div>
</div>